name = "DFUtil"
uuid = "d0f0175c-9793-4b8c-b8d1-59b7835d16e7"
authors = ["Matt H <matt-github@steponnopets.net> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"

[compat]
CSV = "~0.8, 0.9"
DataFrames = "1"
Pipe = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
